version: "3.8"
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
