// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type NewTodo struct {
	Title  string `json:"title"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
